### ISSUE TITLE
Can't login after build

### ISSUE THREAD

**Issue by hongchuanlee** [mac-gallagher/InstagramClone#2]
Hi, the project is amazing

I build successfully but after I sign up, I cannot sign in, is this a database problem?

Thanks !

**Comment by mac-gallagher** [comment]
Thank you! I would start by checking your Firebase security rules.

**Comment by sumit151199** [comment]
> Hi, the project is amazing
> 
> I build successfully but after I sign up, I cannot sign in, is this a database problem?
> 
> Thanks !

How to Register ?
