### ISSUE TITLE
Firebase Realtime Database structure 

### ISSUE THREAD

**Issue by famictech2000** [mac-gallagher/InstagramClone#7]
Can you please share the firebase realtime database structure for this?

**Comment by mac-gallagher** [comment]
Calm down.



![Screen Shot 2020-09-20 at 5 15 03 PM](https://user-images.githubusercontent.com/33521371/93723556-fee5dd00-fb64-11ea-9563-667cbb55ba69.png)
![Screen Shot 2020-09-20 at 5 14 57 PM](https://user-images.githubusercontent.com/33521371/93723557-fee5dd00-fb64-11ea-9490-68cbc46a65db.png)
![Screen Shot 2020-09-20 at 5 14 51 PM](https://user-images.githubusercontent.com/33521371/93723558-ff7e7380-fb64-11ea-98c9-ec24310b26d0.png)
![Screen Shot 2020-09-20 at 5 14 45 PM](https://user-images.githubusercontent.com/33521371/93723559-ff7e7380-fb64-11ea-82c6-a2e935904f9a.png)
![Screen Shot 2020-09-20 at 5 14 39 PM](https://user-images.githubusercontent.com/33521371/93723560-00170a00-fb65-11ea-9cad-10e52109a28b.png)
![Screen Shot 2020-09-20 at 5 14 26 PM](https://user-images.githubusercontent.com/33521371/93723561-00170a00-fb65-11ea-8eee-22dc069c349c.png)
![Screen Shot 2020-09-20 at 5 14 17 PM](https://user-images.githubusercontent.com/33521371/93723562-00170a00-fb65-11ea-8c46-9330c30ea39e.png)

**Comment by famictech2000** [comment]
Quick question. In the "comments" node, is the -LKcvaJsRm6iuriGtY6i the post id followed by -LKvoJyW7MXHDxhvWnE being the comment id?
